library(RODBC)
myconn <-odbcConnect("INED")
TCM <- sqlFetch(myconn, "EE.TCM")
Liens <- sqlFetch(myconn, "EE.Liens")
nodes <- sqlFetch(myconn, "EE.vNodes")
links <- sqlFetch(myconn, "EE.vLinks")
sbGeneal <- sqlFetch(myconn, "EE.vGenealogy",stringsAsFactors=F)
close(myconn)
rm(myconn)

write.csv2(TCM, "input/TCM.csv", row.names = F)
write.csv2(Liens, "input/Liens.csv", row.names = F)
write.csv2(nodes, "input/nodes.csv", row.names = F)
write.csv2(links, "input/links.csv", row.names = F)
write.csv2(sbGeneal, "input/sbGeneal.csv", row.names = F)